default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  
development:
  <<: *default
  database: defaultdb
  username: avnadmin
  password: AVNS_2HzPhRkkZzjr08zvnys
  host: pg-1aea50ac-nyavotraa-2d27.b.aivencloud.com
  port: 25695
